openapi: 3.0.0
info:
  version: 1.0.0
  title: light-start
  description: |-
    这是 [light-start](https://gitee.com/lightgrp/light-start) 的轻量级实现，使用hutool.http处理请求并通过命令行调用codegen-cli生成项目。
servers:
- url: /
externalDocs:
  url: http://localhost:8080/target/
  description: 文件下载
paths:
  /api/json:
    post:
      description: config、configFile不能同时为空，openapilambda仅在2.x版本和Java11以上支持。
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Args'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 错误消息，或者文件路径
          description: 点击上面的“文件下载”链接，拼接返回的message内容，即可下载生成的zip包。
components:
  schemas:
    Args:
      type: object
      properties:
        framework:
          description: rest有3个（其中openapilambda仅版本2.x支持），hybrid有2个，graphql有1个；config和model参考https://github.com/networknt/model-config。
          type: string
          enum:
          - openapi
          - openapikotlin
          - light-hybrid-4j-service
          - light-hybrid-4j-server
          - light-graphql-4j
          - openapilambda
        config:
          description: 配置groupId、artifactId、package等信息的config.json文件内容（clip < config.json）或网址
          type: string
          example: https://gitee.com/lightgrp/light-service/raw/master/model-config/petstore/config.json
        configFile:
          description: 配置文件：config.json
          type: string
          format: binary
        model:
          description: 规范文件base64内容（base64 openapi.yaml | clip）或网址：openapi.yaml、swagger.json、schema.json、schema.graphqls，某些framework可以为空
          type: string
          example: https://gitee.com/lightgrp/light-service/raw/master/model-config/petstore/openapi.yaml
        modelFile:
          description: 规范文件：openapi.yaml、swagger.json、schema.json、schema.graphqls，某些framework可以为空
          type: string
          format: binary
        release:
          description: 版本2.x需JAVA11+支持，且openapilambda仅版本2.x支持
          type: string
          enum:
            - 1.x
            - 2.x
      required:
      - framework
